# Generated by Django 3.2.9 on 2023-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170808_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lga',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
