# Generated by Django 3.2.9 on 2023-05-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_person_lga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state_of_origin',
        ),
    ]
